package sample.camel.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "https://www.w3schools.com/xml/", name = "TempConvertHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempConvertHttpPost {

    @WebMethod(operationName = "CelsiusToFahrenheit")
    @WebResult(name = "string", targetNamespace = "https://www.w3schools.com/xml/", partName = "Body")
    public java.lang.String celsiusToFahrenheit(

        @WebParam(partName = "Celsius", name = "Celsius", targetNamespace = "")
        java.lang.String celsius
    );

    @WebMethod(operationName = "FahrenheitToCelsius")
    @WebResult(name = "string", targetNamespace = "https://www.w3schools.com/xml/", partName = "Body")
    public java.lang.String fahrenheitToCelsius(

        @WebParam(partName = "Fahrenheit", name = "Fahrenheit", targetNamespace = "")
        java.lang.String fahrenheit
    );
}
